# Generated by Django 5.2.3 on 2025-07-16 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_books_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='published_date',
            new_name='published_data',
        ),
    ]
