# Generated by Django 5.2.3 on 2025-07-14 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='published_data',
            new_name='To_be_completed',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='author',
            new_name='description',
        ),
    ]
